version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:4000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - PORT=4000
    #env_file:
    #   - ./.env
