version: "3"
services:
  nginx:
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build:
      context: . #location of dockerfile
      args:
        NODE_ENV: development
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - NODE_ENV=development
    command: npm run dev
