version: "3"
services:
  nginx:
    image: nginx:stable-alpine
  node-app:
    build: .
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://roha:roha@mongo:27017/?authSource=admin
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=roha
      - MONGO_INITDB_ROOT_PASSWORD=roha
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
volumes:
  mongo-db:
